# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anaqueles_por_fila', models.IntegerField()),
                ('direccion', models.TextField()),
                ('filas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnaquelProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('fila', models.IntegerField()),
                ('cantidad_max', models.IntegerField()),
                ('candidad_producto', models.IntegerField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizada', models.DateField(default=datetime.date.today, null=True)),
                ('fecha_prevista', models.DateField(null=True)),
                ('fecha_recibida', models.DateField(null=True)),
                ('cantidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_clasificacion', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('pedidos', models.ManyToManyField(related_name='_proveedor_pedidos_+', through='aplicacion.Pedido', to='aplicacion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_tiempo', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(related_name='_proveedor_productos_+', through='aplicacion.ProveedorProducto', to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='s_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.SubGrupo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Proveedor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='anaquelproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='productos',
            field=models.ManyToManyField(through='aplicacion.AnaquelProducto', to='aplicacion.Producto'),
        ),
    ]
