# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizada', models.DateField(null=True)),
                ('fechaPrevista', models.DateField(null=True)),
                ('fechaRecibida', models.DateField(null=True)),
                ('cantidad', models.CharField(max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proveedor')),
            ],
        ),
    ]
