# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_producto'),
        ('aplicacion', '0004_pedido'),
    ]

    operations = [
    ]
