# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anaqueles_por_fila', models.IntegerField()),
                ('direccion', models.TextField()),
                ('filas', models.IntegerField()),
            ],
        ),
    ]
