# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_merge_20170421_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fechaRealizada', models.CharField(max_length=20)),
                ('cantidad', models.CharField(max_length=20)),
                ('almacen', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Producto'),
        ),
    ]
