# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20170506_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fechaPrevista',
            new_name='fecha_prevista',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fechaRealizada',
            new_name='fecha_realizada',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fechaRecibida',
            new_name='fecha_recibida',
        ),
        migrations.AddField(
            model_name='producto',
            name='almacenAsoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Almacen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
