# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20170506_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='anaqueles_por_fila',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='filas',
        ),
        migrations.AddField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
