# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20170507_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaquelProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('fila', models.IntegerField()),
                ('cantidad_max', models.IntegerField()),
                ('candidad_producto', models.IntegerField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Grupo')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_clasificacion',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pedidos',
            field=models.ManyToManyField(related_name='_proveedor_pedidos_+', through='aplicacion.Pedido', to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(related_name='_proveedor_productos_+', through='aplicacion.ProveedorProducto', to='aplicacion.Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proveedorproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AlterField(
            model_name='proveedorproducto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Proveedor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='anaquelproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='productos',
            field=models.ManyToManyField(through='aplicacion.AnaquelProducto', to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='s_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.SubGrupo'),
        ),
    ]
