# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CUsuario',
            new_name='Usuario',
        ),
    ]
